### ISSUE TITLE
crash when right clicking on the frequency domain plot

### ISSUE THREAD

**Issue by buha** [analogdevicesinc/iio-oscilloscope#205]
`osc` crashes every time I right click on the frequency plot.

Using `osc v0.10.r28.9b9a441-1` on Manjaro Linux.

GTK2: 2.24.32-1
Glib2: 2.62.2-1

```
$ gdb osc
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from osc...
(No debugging symbols found in osc)
(gdb) r
Starting program: /usr/bin/osc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 9545]
[New Thread 0x7ffff164f700 (LWP 9546)]
[New Thread 0x7ffff0e4e700 (LWP 9547)]

(osc:9541): GVFS-RemoteVolumeMonitor-WARNING **: 10:36:10.878: remote volume monitor with dbus name org.gtk.vfs.GoaVolumeMonitor is not supported
[New Thread 0x7fffebfff700 (LWP 9548)]
[New Thread 0x7fffeb7fe700 (LWP 9549)]
[New Thread 0x7fffeaffd700 (LWP 9550)]
[Thread 0x7fffeaffd700 (LWP 9550) exited]
[Thread 0x7fffeb7fe700 (LWP 9549) exited]
[Detaching after vfork from child process 9552]
[New Thread 0x7fffeb7fe700 (LWP 9554)]
[Thread 0x7fffeb7fe700 (LWP 9554) exited]
Found plugin: FMComms1
Found plugin: Partial Reconfiguration
Found plugin: CN0357
Found plugin: DAQ1/2/3
Found plugin: AD5628-1
Found plugin: AD9371 Advanced
Found plugin: LIDAR
Found plugin: ADRV9009 Advanced
Found plugin: CN0508
Found plugin: AD6676
Found plugin: DMM
Found plugin: ad9739a
Found plugin: AD936X
Found plugin: ADRV9009
Found plugin: Spectrum Analyzer
Found plugin: Motor Control
Found plugin: Debug
Found plugin: FMComms6
Found plugin: AD7303
Found plugin: SCPI
Found plugin: FMCOMMS11
Found plugin: FMCADC3
Found plugin: AD9371
Found plugin: FMComms5
Found plugin: AD936X Advanced
[New Thread 0x7fffeb7fe700 (LWP 9555)]
[New Thread 0x7fffeaffd700 (LWP 9556)]
[New Thread 0x7fffea7fc700 (LWP 9557)]
[New Thread 0x7fffe9ffb700 (LWP 9558)]
[Thread 0x7fffeaffd700 (LWP 9556) exited]
[New Thread 0x7fffe97fa700 (LWP 9559)]
[Thread 0x7fffe9ffb700 (LWP 9558) exited]
[New Thread 0x7fffe8ff9700 (LWP 9560)]
[New Thread 0x7fffcffff700 (LWP 9561)]
[New Thread 0x7fffcf7fe700 (LWP 9562)]
[New Thread 0x7fffceffd700 (LWP 9563)]
Updating widgets...
[Thread 0x7fffeb7fe700 (LWP 9555) exited]
Updating FIR filter...
Loaded plugin: ADRV9009 Advanced
Loaded plugin: DMM
[Thread 0x7fffea7fc700 (LWP 9557) exited]
Loaded plugin: ADRV9009
Loaded plugin: Debug
[New Thread 0x7fffe9ffb700 (LWP 9564)]
[New Thread 0x7fffea7fc700 (LWP 9565)]
[Thread 0x7fffea7fc700 (LWP 9565) exited]
[Thread 0x7fffcffff700 (LWP 9561) exited]
[Thread 0x7fffceffd700 (LWP 9563) exited]
[Thread 0x7fffe97fa700 (LWP 9559) exited]
[Thread 0x7fffcf7fe700 (LWP 9562) exited]
[Thread 0x7fffebfff700 (LWP 9548) exited]
[New Thread 0x7fffebfff700 (LWP 9566)]
[Thread 0x7fffebfff700 (LWP 9566) exited]
[Thread 0x7fffe9ffb700 (LWP 9564) exited]
FPS: 0










[Thread 0x7fffe8ff9700 (LWP 9560) exited]

Thread 1 "osc" received signal SIGSEGV, Segmentation fault.
0x00007ffff74fa18c in g_type_check_instance_is_fundamentally_a () from /usr/lib/libgobject-2.0.so.0
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) bt full
#0  0x00007ffff74fa18c in g_type_check_instance_is_fundamentally_a () at /usr/lib/libgobject-2.0.so.0
#1  0x00007ffff75161f9 in g_signal_connect_object () at /usr/lib/libgobject-2.0.so.0
#2  0x00007ffff7495cc5 in  () at /usr/lib/libosc.so.0
#3  0x00007ffff794a7cc in  () at /usr/lib/libgtk-x11-2.0.so.0
#4  0x00007ffff7517d5a in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff750588e in  () at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff7508f1c in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff750a7f0 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff7a65235 in  () at /usr/lib/libgtk-x11-2.0.so.0
#9  0x00007ffff7948a0e in gtk_propagate_event () at /usr/lib/libgtk-x11-2.0.so.0
#10 0x00007ffff7948e43 in gtk_main_do_event () at /usr/lib/libgtk-x11-2.0.so.0
#11 0x00007ffff75c1d5e in  () at /usr/lib/libgdk-x11-2.0.so.0
#12 0x00007ffff7ec33ee in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#13 0x00007ffff7ec5201 in  () at /usr/lib/libglib-2.0.so.0
#14 0x00007ffff7ec6113 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff7947df3 in gtk_main () at /usr/lib/libgtk-x11-2.0.so.0
#16 0x00005555555571bf in main ()
(gdb) q
```
```
ldd /usr/bin/osc-master-g26da8df-dirty 
linux-vdso.so.1 (0x00007fffa5d63000)
libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007fdffb074000)
libgtk-x11-2.0.so.0 => /usr/lib/libgtk-x11-2.0.so.0 (0x00007fdffaa37000)
libgdk-x11-2.0.so.0 => /usr/lib/libgdk-x11-2.0.so.0 (0x00007fdffa783000)
libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x00007fdffa75d000)
libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007fdffa701000)
libiio.so.0 => /usr/lib/libiio.so.0 (0x00007fdffa6e3000)
libosc.so.0 => /usr/lib/libosc.so.0 (0x00007fdffa69b000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007fdffa4d4000)
libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007fdffa461000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fdffa43f000)
libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007fdffa43a000)
libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007fdffa42a000)
libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fdffa2e8000)
libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007fdffa0e2000)
libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0x00007fdffa0b9000)
libcairo.so.2 => /usr/lib/libcairo.so.2 (0x00007fdff9f95000)
libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007fdff9de5000)
libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007fdff9dce000)
libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x00007fdff9d7e000)
libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007fdff9d37000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007fdff9bf1000)
libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007fdff9be4000)
libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007fdff99e1000)
libXi.so.6 => /usr/lib/libXi.so.6 (0x00007fdff99ce000)
libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007fdff99bf000)
libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x00007fdff99b3000)
libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x00007fdff99ae000)
libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007fdff99a9000)
libXext.so.6 => /usr/lib/libXext.so.6 (0x00007fdff9994000)
libffi.so.6 => /usr/lib/libffi.so.6 (0x00007fdff9989000)
libusb-1.0.so.0 => /usr/lib/libusb-1.0.so.0 (0x00007fdff996b000)
libserialport.so.0 => /usr/lib/libserialport.so.0 (0x00007fdff9959000)
libavahi-client.so.3 => /usr/lib/libavahi-client.so.3 (0x00007fdff9945000)
libavahi-common.so.3 => /usr/lib/libavahi-common.so.3 (0x00007fdff9937000)
libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007fdff97cf000)
libgtkdatabox-0.9.3.so.1 => /usr/lib/libgtkdatabox-0.9.3.so.1 (0x00007fdff97af000)
libfftw3.so.3 => /usr/lib/libfftw3.so.3 (0x00007fdff9383000)
libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007fdff92f7000)
libjansson.so.4 => /usr/lib/libjansson.so.4 (0x00007fdff92e8000)
libmatio.so.9 => /usr/lib/libmatio.so.9 (0x00007fdff9282000)
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fdffb1f0000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fdff927d000)
libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fdff9251000)
libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x00007fdff91a7000)
libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007fdff90d9000)
libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fdff90a1000)
libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007fdff909c000)
libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007fdff908c000)
libz.so.1 => /usr/lib/libz.so.1 (0x00007fdff8e73000)
librt.so.1 => /usr/lib/librt.so.1 (0x00007fdff8e68000)
libmount.so.1 => /usr/lib/libmount.so.1 (0x00007fdff8e08000)
libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007fdff8def000)
libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007fdff8ceb000)
libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x00007fdff8ccc000)
libthai.so.0 => /usr/lib/libthai.so.0 (0x00007fdff8cbf000)
libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007fdff8c92000)
libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007fdff8c89000)
libudev.so.1 => /usr/lib/libudev.so.1 (0x00007fdff8c5f000)
libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007fdff8c15000)
libicuuc.so.64 => /usr/lib/libicuuc.so.64 (0x00007fdff8a3b000)
liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007fdff8815000)
libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0x00007fdff87ed000)
libidn2.so.0 => /usr/lib/libidn2.so.0 (0x00007fdff87ce000)
libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007fdff878e000)
libpsl.so.5 => /usr/lib/libpsl.so.5 (0x00007fdff877b000)
libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007fdff86e9000)
libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007fdff8418000)
libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00007fdff83c8000)
libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00007fdff82da000)
libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00007fdff82a5000)
libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007fdff829f000)
libhdf5.so.103 => /usr/lib/libhdf5.so.103 (0x00007fdff7f1c000)
libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fdff7f17000)
libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fdff7f0f000)
libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007fdff7efc000)
libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007fdff7ea6000)
libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007fdff7e7f000)
libdatrie.so.1 => /usr/lib/libdatrie.so.1 (0x00007fdff7c78000)
libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007fdff7bd1000)
libicudata.so.64 => /usr/lib/libicudata.so.64 (0x00007fdff618d000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fdff5fa3000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fdff5f89000)
libunistring.so.2 => /usr/lib/libunistring.so.2 (0x00007fdff5c07000)
libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007fdff5bf7000)
libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007fdff5bf0000)
libsz.so.2 => /usr/lib/libsz.so.2 (0x00007fdff5beb000)
liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007fdff5bc9000)
libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007fdff5aa9000)
libaec.so.0 => /usr/lib/libaec.so.0 (0x00007fdff5a9f000)
libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007fdff5a7c000)
```

**Comment by buha** [comment]
Checked master branch after fix, doesn't occur anymore.
Thanks
